/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDietaRouteImport } from './routes/_authenticated/dieta'
import { Route as AuthenticatedDespensaRouteImport } from './routes/_authenticated/despensa'
import { Route as AuthenticatedDespensaIndexRouteImport } from './routes/_authenticated/despensa.index'
import { Route as AuthenticatedDespensaStockRouteImport } from './routes/_authenticated/despensa.stock'
import { Route as AuthenticatedDespensaImportarRouteImport } from './routes/_authenticated/despensa.importar'
import { Route as AuthenticatedDespensaExportarRouteImport } from './routes/_authenticated/despensa.exportar'
import { Route as AuthenticatedDespensaAuditoriaRouteImport } from './routes/_authenticated/despensa.auditoria'
import { Route as AuthenticatedDespensaStockIndexRouteImport } from './routes/_authenticated/despensa.stock.index'
import { Route as AuthenticatedDespensaStockNuevoRouteImport } from './routes/_authenticated/despensa.stock.nuevo'
import { Route as AuthenticatedDespensaProductosNuevoRouteImport } from './routes/_authenticated/despensa.productos.nuevo'
import { Route as AuthenticatedDespensaProductosProductIdRouteImport } from './routes/_authenticated/despensa.productos.$productId'
import { Route as AuthenticatedDespensaStockStockItemIdHistorialRouteImport } from './routes/_authenticated/despensa.stock.$stockItemId.historial'
import { Route as AuthenticatedDespensaStockStockItemIdEditarRouteImport } from './routes/_authenticated/despensa.stock.$stockItemId.editar'
import { Route as AuthenticatedDespensaProductosProductIdEditarRouteImport } from './routes/_authenticated/despensa.productos.$productId.editar'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDietaRoute = AuthenticatedDietaRouteImport.update({
  id: '/dieta',
  path: '/dieta',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDespensaRoute = AuthenticatedDespensaRouteImport.update({
  id: '/despensa',
  path: '/despensa',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDespensaIndexRoute =
  AuthenticatedDespensaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDespensaRoute,
  } as any)
const AuthenticatedDespensaStockRoute =
  AuthenticatedDespensaStockRouteImport.update({
    id: '/stock',
    path: '/stock',
    getParentRoute: () => AuthenticatedDespensaRoute,
  } as any)
const AuthenticatedDespensaImportarRoute =
  AuthenticatedDespensaImportarRouteImport.update({
    id: '/importar',
    path: '/importar',
    getParentRoute: () => AuthenticatedDespensaRoute,
  } as any)
const AuthenticatedDespensaExportarRoute =
  AuthenticatedDespensaExportarRouteImport.update({
    id: '/exportar',
    path: '/exportar',
    getParentRoute: () => AuthenticatedDespensaRoute,
  } as any)
const AuthenticatedDespensaAuditoriaRoute =
  AuthenticatedDespensaAuditoriaRouteImport.update({
    id: '/auditoria',
    path: '/auditoria',
    getParentRoute: () => AuthenticatedDespensaRoute,
  } as any)
const AuthenticatedDespensaStockIndexRoute =
  AuthenticatedDespensaStockIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDespensaStockRoute,
  } as any)
const AuthenticatedDespensaStockNuevoRoute =
  AuthenticatedDespensaStockNuevoRouteImport.update({
    id: '/nuevo',
    path: '/nuevo',
    getParentRoute: () => AuthenticatedDespensaStockRoute,
  } as any)
const AuthenticatedDespensaProductosNuevoRoute =
  AuthenticatedDespensaProductosNuevoRouteImport.update({
    id: '/productos/nuevo',
    path: '/productos/nuevo',
    getParentRoute: () => AuthenticatedDespensaRoute,
  } as any)
const AuthenticatedDespensaProductosProductIdRoute =
  AuthenticatedDespensaProductosProductIdRouteImport.update({
    id: '/productos/$productId',
    path: '/productos/$productId',
    getParentRoute: () => AuthenticatedDespensaRoute,
  } as any)
const AuthenticatedDespensaStockStockItemIdHistorialRoute =
  AuthenticatedDespensaStockStockItemIdHistorialRouteImport.update({
    id: '/$stockItemId/historial',
    path: '/$stockItemId/historial',
    getParentRoute: () => AuthenticatedDespensaStockRoute,
  } as any)
const AuthenticatedDespensaStockStockItemIdEditarRoute =
  AuthenticatedDespensaStockStockItemIdEditarRouteImport.update({
    id: '/$stockItemId/editar',
    path: '/$stockItemId/editar',
    getParentRoute: () => AuthenticatedDespensaStockRoute,
  } as any)
const AuthenticatedDespensaProductosProductIdEditarRoute =
  AuthenticatedDespensaProductosProductIdEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => AuthenticatedDespensaProductosProductIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/despensa': typeof AuthenticatedDespensaRouteWithChildren
  '/dieta': typeof AuthenticatedDietaRoute
  '/despensa/auditoria': typeof AuthenticatedDespensaAuditoriaRoute
  '/despensa/exportar': typeof AuthenticatedDespensaExportarRoute
  '/despensa/importar': typeof AuthenticatedDespensaImportarRoute
  '/despensa/stock': typeof AuthenticatedDespensaStockRouteWithChildren
  '/despensa/': typeof AuthenticatedDespensaIndexRoute
  '/despensa/productos/$productId': typeof AuthenticatedDespensaProductosProductIdRouteWithChildren
  '/despensa/productos/nuevo': typeof AuthenticatedDespensaProductosNuevoRoute
  '/despensa/stock/nuevo': typeof AuthenticatedDespensaStockNuevoRoute
  '/despensa/stock/': typeof AuthenticatedDespensaStockIndexRoute
  '/despensa/productos/$productId/editar': typeof AuthenticatedDespensaProductosProductIdEditarRoute
  '/despensa/stock/$stockItemId/editar': typeof AuthenticatedDespensaStockStockItemIdEditarRoute
  '/despensa/stock/$stockItemId/historial': typeof AuthenticatedDespensaStockStockItemIdHistorialRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dieta': typeof AuthenticatedDietaRoute
  '/despensa/auditoria': typeof AuthenticatedDespensaAuditoriaRoute
  '/despensa/exportar': typeof AuthenticatedDespensaExportarRoute
  '/despensa/importar': typeof AuthenticatedDespensaImportarRoute
  '/despensa': typeof AuthenticatedDespensaIndexRoute
  '/despensa/productos/$productId': typeof AuthenticatedDespensaProductosProductIdRouteWithChildren
  '/despensa/productos/nuevo': typeof AuthenticatedDespensaProductosNuevoRoute
  '/despensa/stock/nuevo': typeof AuthenticatedDespensaStockNuevoRoute
  '/despensa/stock': typeof AuthenticatedDespensaStockIndexRoute
  '/despensa/productos/$productId/editar': typeof AuthenticatedDespensaProductosProductIdEditarRoute
  '/despensa/stock/$stockItemId/editar': typeof AuthenticatedDespensaStockStockItemIdEditarRoute
  '/despensa/stock/$stockItemId/historial': typeof AuthenticatedDespensaStockStockItemIdHistorialRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/despensa': typeof AuthenticatedDespensaRouteWithChildren
  '/_authenticated/dieta': typeof AuthenticatedDietaRoute
  '/_authenticated/despensa/auditoria': typeof AuthenticatedDespensaAuditoriaRoute
  '/_authenticated/despensa/exportar': typeof AuthenticatedDespensaExportarRoute
  '/_authenticated/despensa/importar': typeof AuthenticatedDespensaImportarRoute
  '/_authenticated/despensa/stock': typeof AuthenticatedDespensaStockRouteWithChildren
  '/_authenticated/despensa/': typeof AuthenticatedDespensaIndexRoute
  '/_authenticated/despensa/productos/$productId': typeof AuthenticatedDespensaProductosProductIdRouteWithChildren
  '/_authenticated/despensa/productos/nuevo': typeof AuthenticatedDespensaProductosNuevoRoute
  '/_authenticated/despensa/stock/nuevo': typeof AuthenticatedDespensaStockNuevoRoute
  '/_authenticated/despensa/stock/': typeof AuthenticatedDespensaStockIndexRoute
  '/_authenticated/despensa/productos/$productId/editar': typeof AuthenticatedDespensaProductosProductIdEditarRoute
  '/_authenticated/despensa/stock/$stockItemId/editar': typeof AuthenticatedDespensaStockStockItemIdEditarRoute
  '/_authenticated/despensa/stock/$stockItemId/historial': typeof AuthenticatedDespensaStockStockItemIdHistorialRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/despensa'
    | '/dieta'
    | '/despensa/auditoria'
    | '/despensa/exportar'
    | '/despensa/importar'
    | '/despensa/stock'
    | '/despensa/'
    | '/despensa/productos/$productId'
    | '/despensa/productos/nuevo'
    | '/despensa/stock/nuevo'
    | '/despensa/stock/'
    | '/despensa/productos/$productId/editar'
    | '/despensa/stock/$stockItemId/editar'
    | '/despensa/stock/$stockItemId/historial'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dieta'
    | '/despensa/auditoria'
    | '/despensa/exportar'
    | '/despensa/importar'
    | '/despensa'
    | '/despensa/productos/$productId'
    | '/despensa/productos/nuevo'
    | '/despensa/stock/nuevo'
    | '/despensa/stock'
    | '/despensa/productos/$productId/editar'
    | '/despensa/stock/$stockItemId/editar'
    | '/despensa/stock/$stockItemId/historial'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/despensa'
    | '/_authenticated/dieta'
    | '/_authenticated/despensa/auditoria'
    | '/_authenticated/despensa/exportar'
    | '/_authenticated/despensa/importar'
    | '/_authenticated/despensa/stock'
    | '/_authenticated/despensa/'
    | '/_authenticated/despensa/productos/$productId'
    | '/_authenticated/despensa/productos/nuevo'
    | '/_authenticated/despensa/stock/nuevo'
    | '/_authenticated/despensa/stock/'
    | '/_authenticated/despensa/productos/$productId/editar'
    | '/_authenticated/despensa/stock/$stockItemId/editar'
    | '/_authenticated/despensa/stock/$stockItemId/historial'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dieta': {
      id: '/_authenticated/dieta'
      path: '/dieta'
      fullPath: '/dieta'
      preLoaderRoute: typeof AuthenticatedDietaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/despensa': {
      id: '/_authenticated/despensa'
      path: '/despensa'
      fullPath: '/despensa'
      preLoaderRoute: typeof AuthenticatedDespensaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/despensa/': {
      id: '/_authenticated/despensa/'
      path: '/'
      fullPath: '/despensa/'
      preLoaderRoute: typeof AuthenticatedDespensaIndexRouteImport
      parentRoute: typeof AuthenticatedDespensaRoute
    }
    '/_authenticated/despensa/stock': {
      id: '/_authenticated/despensa/stock'
      path: '/stock'
      fullPath: '/despensa/stock'
      preLoaderRoute: typeof AuthenticatedDespensaStockRouteImport
      parentRoute: typeof AuthenticatedDespensaRoute
    }
    '/_authenticated/despensa/importar': {
      id: '/_authenticated/despensa/importar'
      path: '/importar'
      fullPath: '/despensa/importar'
      preLoaderRoute: typeof AuthenticatedDespensaImportarRouteImport
      parentRoute: typeof AuthenticatedDespensaRoute
    }
    '/_authenticated/despensa/exportar': {
      id: '/_authenticated/despensa/exportar'
      path: '/exportar'
      fullPath: '/despensa/exportar'
      preLoaderRoute: typeof AuthenticatedDespensaExportarRouteImport
      parentRoute: typeof AuthenticatedDespensaRoute
    }
    '/_authenticated/despensa/auditoria': {
      id: '/_authenticated/despensa/auditoria'
      path: '/auditoria'
      fullPath: '/despensa/auditoria'
      preLoaderRoute: typeof AuthenticatedDespensaAuditoriaRouteImport
      parentRoute: typeof AuthenticatedDespensaRoute
    }
    '/_authenticated/despensa/stock/': {
      id: '/_authenticated/despensa/stock/'
      path: '/'
      fullPath: '/despensa/stock/'
      preLoaderRoute: typeof AuthenticatedDespensaStockIndexRouteImport
      parentRoute: typeof AuthenticatedDespensaStockRoute
    }
    '/_authenticated/despensa/stock/nuevo': {
      id: '/_authenticated/despensa/stock/nuevo'
      path: '/nuevo'
      fullPath: '/despensa/stock/nuevo'
      preLoaderRoute: typeof AuthenticatedDespensaStockNuevoRouteImport
      parentRoute: typeof AuthenticatedDespensaStockRoute
    }
    '/_authenticated/despensa/productos/nuevo': {
      id: '/_authenticated/despensa/productos/nuevo'
      path: '/productos/nuevo'
      fullPath: '/despensa/productos/nuevo'
      preLoaderRoute: typeof AuthenticatedDespensaProductosNuevoRouteImport
      parentRoute: typeof AuthenticatedDespensaRoute
    }
    '/_authenticated/despensa/productos/$productId': {
      id: '/_authenticated/despensa/productos/$productId'
      path: '/productos/$productId'
      fullPath: '/despensa/productos/$productId'
      preLoaderRoute: typeof AuthenticatedDespensaProductosProductIdRouteImport
      parentRoute: typeof AuthenticatedDespensaRoute
    }
    '/_authenticated/despensa/stock/$stockItemId/historial': {
      id: '/_authenticated/despensa/stock/$stockItemId/historial'
      path: '/$stockItemId/historial'
      fullPath: '/despensa/stock/$stockItemId/historial'
      preLoaderRoute: typeof AuthenticatedDespensaStockStockItemIdHistorialRouteImport
      parentRoute: typeof AuthenticatedDespensaStockRoute
    }
    '/_authenticated/despensa/stock/$stockItemId/editar': {
      id: '/_authenticated/despensa/stock/$stockItemId/editar'
      path: '/$stockItemId/editar'
      fullPath: '/despensa/stock/$stockItemId/editar'
      preLoaderRoute: typeof AuthenticatedDespensaStockStockItemIdEditarRouteImport
      parentRoute: typeof AuthenticatedDespensaStockRoute
    }
    '/_authenticated/despensa/productos/$productId/editar': {
      id: '/_authenticated/despensa/productos/$productId/editar'
      path: '/editar'
      fullPath: '/despensa/productos/$productId/editar'
      preLoaderRoute: typeof AuthenticatedDespensaProductosProductIdEditarRouteImport
      parentRoute: typeof AuthenticatedDespensaProductosProductIdRoute
    }
  }
}

interface AuthenticatedDespensaStockRouteChildren {
  AuthenticatedDespensaStockNuevoRoute: typeof AuthenticatedDespensaStockNuevoRoute
  AuthenticatedDespensaStockIndexRoute: typeof AuthenticatedDespensaStockIndexRoute
  AuthenticatedDespensaStockStockItemIdEditarRoute: typeof AuthenticatedDespensaStockStockItemIdEditarRoute
  AuthenticatedDespensaStockStockItemIdHistorialRoute: typeof AuthenticatedDespensaStockStockItemIdHistorialRoute
}

const AuthenticatedDespensaStockRouteChildren: AuthenticatedDespensaStockRouteChildren =
  {
    AuthenticatedDespensaStockNuevoRoute: AuthenticatedDespensaStockNuevoRoute,
    AuthenticatedDespensaStockIndexRoute: AuthenticatedDespensaStockIndexRoute,
    AuthenticatedDespensaStockStockItemIdEditarRoute:
      AuthenticatedDespensaStockStockItemIdEditarRoute,
    AuthenticatedDespensaStockStockItemIdHistorialRoute:
      AuthenticatedDespensaStockStockItemIdHistorialRoute,
  }

const AuthenticatedDespensaStockRouteWithChildren =
  AuthenticatedDespensaStockRoute._addFileChildren(
    AuthenticatedDespensaStockRouteChildren,
  )

interface AuthenticatedDespensaProductosProductIdRouteChildren {
  AuthenticatedDespensaProductosProductIdEditarRoute: typeof AuthenticatedDespensaProductosProductIdEditarRoute
}

const AuthenticatedDespensaProductosProductIdRouteChildren: AuthenticatedDespensaProductosProductIdRouteChildren =
  {
    AuthenticatedDespensaProductosProductIdEditarRoute:
      AuthenticatedDespensaProductosProductIdEditarRoute,
  }

const AuthenticatedDespensaProductosProductIdRouteWithChildren =
  AuthenticatedDespensaProductosProductIdRoute._addFileChildren(
    AuthenticatedDespensaProductosProductIdRouteChildren,
  )

interface AuthenticatedDespensaRouteChildren {
  AuthenticatedDespensaAuditoriaRoute: typeof AuthenticatedDespensaAuditoriaRoute
  AuthenticatedDespensaExportarRoute: typeof AuthenticatedDespensaExportarRoute
  AuthenticatedDespensaImportarRoute: typeof AuthenticatedDespensaImportarRoute
  AuthenticatedDespensaStockRoute: typeof AuthenticatedDespensaStockRouteWithChildren
  AuthenticatedDespensaIndexRoute: typeof AuthenticatedDespensaIndexRoute
  AuthenticatedDespensaProductosProductIdRoute: typeof AuthenticatedDespensaProductosProductIdRouteWithChildren
  AuthenticatedDespensaProductosNuevoRoute: typeof AuthenticatedDespensaProductosNuevoRoute
}

const AuthenticatedDespensaRouteChildren: AuthenticatedDespensaRouteChildren = {
  AuthenticatedDespensaAuditoriaRoute: AuthenticatedDespensaAuditoriaRoute,
  AuthenticatedDespensaExportarRoute: AuthenticatedDespensaExportarRoute,
  AuthenticatedDespensaImportarRoute: AuthenticatedDespensaImportarRoute,
  AuthenticatedDespensaStockRoute: AuthenticatedDespensaStockRouteWithChildren,
  AuthenticatedDespensaIndexRoute: AuthenticatedDespensaIndexRoute,
  AuthenticatedDespensaProductosProductIdRoute:
    AuthenticatedDespensaProductosProductIdRouteWithChildren,
  AuthenticatedDespensaProductosNuevoRoute:
    AuthenticatedDespensaProductosNuevoRoute,
}

const AuthenticatedDespensaRouteWithChildren =
  AuthenticatedDespensaRoute._addFileChildren(
    AuthenticatedDespensaRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDespensaRoute: typeof AuthenticatedDespensaRouteWithChildren
  AuthenticatedDietaRoute: typeof AuthenticatedDietaRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDespensaRoute: AuthenticatedDespensaRouteWithChildren,
  AuthenticatedDietaRoute: AuthenticatedDietaRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
